flaskr/blog/models.py
from sqlalchemy import Column, DateTime, ForeignKey, Integer, String
from sqlalchemy.orm import relationship
from sqlalchemy.sql import func

from .. import db


class Post(db.Model):
    __tablename__ = 'post'
    id = Column(Integer, primary_key=True)
    author_id = Column(Integer, ForeignKey('site_user.id'), nullable=False)
    created = Column(
        DateTime(timezone=True), server_default=func.now(), nullable=False)
    title = Column(String(50), nullable=False)
    body = Column(String(500), nullable=False)
    author = relationship('User')

    def __init__(self, author_id=None, title=None, body=None):
        self.author_id = author_id
        self.title = title
        self.body = body

    def __repr__(self):
        return '<Title %r>' % (self.title)

flaskr/blog/forms.py
from flask_wtf import FlaskForm
from wtforms import SubmitField, TextField, TextAreaField
from wtforms.validators import DataRequired, Length


class CreateForm(FlaskForm):
    title = TextField(
        'Title', validators=[DataRequired(), Length(1, 50)])
    body = TextAreaField('Body', validators=[DataRequired(), Length(1, 500)])
    register = SubmitField('Register')


class UpdateForm(FlaskForm):
    title = TextField(
        'Title', validators=[DataRequired(), Length(1, 50)])
    body = TextAreaField('Body', validators=[DataRequired(), Length(1, 500)])
    save = SubmitField('Save')
    delete = SubmitField('Delete')

flaskr/__init__.py
import os
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager

db = SQLAlchemy()
login_manager = LoginManager()


def create_app(test_config=None):
    # create and configure the app
    app = Flask(__name__, instance_relative_config=True)
    app.config.from_mapping(
        SECRET_KEY='dev',
        DATABASE=os.path.join(app.instance_path, 'flaskr.db'),
    )
    if test_config is None:
        # load the instance config, if it exists, when not testing
        app.config.from_pyfile('config.py', silent=True)
    else:
        # load the test config if passed in
        app.config.from_mapping(test_config)

    db.init_app(app)
    login_manager.init_app(app)

    # ensure the instance folder exists
    try:
        os.makedirs(app.instance_path)
    except OSError:
        pass

    if app.config['GITHUB_FOUND']:
        print('GITHUB_FOUND')
        from flask_dance.contrib.github import make_github_blueprint
        github_bp = make_github_blueprint(redirect_url='/auth/github_callback')
        app.register_blueprint(github_bp, url_prefix='/login')

    if app.config['GOOGLE_FOUND']:
        print('GOOGLE_FOUND')
        from flask_dance.contrib.google import make_google_blueprint
        google_bp = make_google_blueprint(redirect_url='/auth/google_callback')
        app.register_blueprint(google_bp, url_prefix='/login')

    from .auth import blueprint as auth_bp
    app.register_blueprint(auth_bp.bp)

    from .blog import blueprint as blog_bp
    app.register_blueprint(blog_bp.bp)
    app.add_url_rule('/', endpoint='index')

    return app

flaskr/blog/blueprint.py
from flask import (
    Blueprint, flash, redirect, render_template, url_for
)
from flask_login import current_user, login_required
from werkzeug.exceptions import abort

from flaskr import db
from ..auth.models import User
from .forms import CreateForm, UpdateForm
from .models import Post

bp = Blueprint('blog', __name__)


@bp.route('/create', methods=('GET', 'POST'))
@login_required
def create():
    form = CreateForm()
    if form.validate_on_submit():
        title = form.title.data
        body = form.body.data
        error = None

        if not title:
            error = 'Title is required.'

        if error is not None:
            flash(error)
        else:
            post = Post(current_user.id, title, body)
            db.session.add(post)
            db.session.commit()
            return redirect(url_for('blog.index'))

    return render_template('blog/create.html', form=form)


@bp.route('/<int:id>/delete', methods=('POST',))
@login_required
def delete(id):
    get_post(id)
    Post.query.filter_by(id=id).delete()
    db.session.commit()
    return redirect(url_for('blog.index'))


def get_post(id, check_author=True):
    post = Post.query.join(
        User, Post.author_id == User.id).filter(Post.id == id).first()

    if post is None:
        abort(404, "Post id {0} doesn't exist.".format(id))

    if check_author and post.author_id != current_user.id:
        abort(403)

    return post


@bp.route('/')
@login_required
def index():
    posts = Post.query.join(
        User, Post.author_id == User.id).order_by(Post.created.desc()).all()
    return render_template('blog/index.html', posts=posts)


@bp.route('/<int:id>/update', methods=('GET', 'POST'))
@login_required
def update(id):
    post = get_post(id)
    form = UpdateForm()
    if form.validate_on_submit():
        title = form.title.data
        body = form.body.data
        error = None

        if not title:
            error = 'Title is required.'

        if error is not None:
            flash(error)
        else:
            post = Post.query.filter_by(id=id).first()
            post.title = title
            post.body = body
            db.session.commit()
            return redirect(url_for('blog.index'))

    return render_template('blog/update.html', post=post, form=form)

flaskr/templates/base.html
<!doctype html>
<title>{% block title %}{% endblock %} - Flaskr</title>
<link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
<nav>
  <h1>Flaskr</h1>
  <ul>
    {% if current_user.is_authenticated %}
      <li><span>{{ current_user.name }}</span>
      <li><a href="{{ url_for('auth.logout') }}">Log Out</a>
    {% else %}
      <li><a href="{{ url_for('auth.login') }}">Log In</a>
    {% endif %}
  </ul>
</nav>
<section class="content">
  <header>
    {% block header %}{% endblock %}
  </header>
  {% for message in get_flashed_messages() %}
    <div class="flash">{{ message }}</div>
  {% endfor %}
  {% block content %}{% endblock %}
</section>

flaskr/templates/blog/create.html
{% extends 'base.html' %}

{% block header %}
  <h1>{% block title %}New Post{% endblock %}</h1>
{% endblock %}

{% block content %}
  <form method="post">
    {{ form.hidden_tag() }}
    {{ form.title.label }}
    {{ form.title() }}
    {{ form.body.label }}
    {{ form.body() }}
    {{ form.register() }}
  </form>
{% endblock %}

flaskr/templates/blog/index.html
{% extends 'base.html' %}

{% block header %}
  <h1>{% block title %}Posts{% endblock %}</h1>
  {% if current_user.is_authenticated %}
    <a class="action" href="{{ url_for('blog.create') }}">New</a>
  {% endif %}
{% endblock %}

{% block content %}
  {% for post in posts %}
    <article class="post">
      <header>
        <div>
          <h1>{{ post.title }}</h1>
          <div class="about">by {{ post.author.name }} on {{ post.created }}</div>
        </div>
        {% if current_user.id == post.author_id %}
          <a class="action" href="{{ url_for('blog.update', id=post.id) }}">Edit</a>
        {% endif %}
      </header>
      <p class="body">{{ post.body }}</p>
    </article>
    {% if not loop.last %}
      <hr>
    {% endif %}
  {% endfor %}
{% endblock %}

flaskr/templates/blog/update.html
{% extends 'base.html' %}

{% block header %}
  <h1>{% block title %}Edit "{{ post.title }}"{% endblock %}</h1>
{% endblock %}

{% block content %}
  <form method="post">
    {{ form.hidden_tag() }}
    {{ form.title.label }}
    {{ form.title(value=(request.form['title'] or post.title)) }}
    <!-- Workaround to populate textarea as proposed in https://stackoverflow.com/questions/5117479/wtforms-how-to-prepopulate-a-textarea-field -->
    {% set f = form.body.process_data(request.form['body'] or post['body']) %}
    {{ form.body() }}
    {{ form.save() }}
  </form>
  <hr>
  <form action="{{ url_for('blog.delete', id=post.id) }}" method="post">
    {{ form.hidden_tag() }}
    {{ form.delete(onclick="return confirm('Are you sure?');") }}
  </form>
{% endblock %}